# Generated by Django 2.1.1 on 2018-12-27 15:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cycles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('user_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=300, unique=True)),
                ('first_name', models.CharField(max_length=30, null=True)),
                ('last_name', models.CharField(max_length=30, null=True)),
                ('direct_manager', models.CharField(max_length=30, null=True)),
                ('years_of_experience', models.IntegerField(null=True)),
                ('years_within_organization', models.IntegerField(null=True)),
                ('years_in_role', models.IntegerField(null=True)),
                ('study_field', models.CharField(max_length=30, null=True)),
                ('is_mentor', models.BooleanField(default=False)),
                ('work_location', models.CharField(max_length=30, null=True)),
                ('position', models.CharField(max_length=30, null=True)),
                ('departement', models.CharField(max_length=30, null=True)),
                ('cycles', models.ManyToManyField(blank=True, related_name='employee', to='cycles.Cycle')),
                ('matched', models.ManyToManyField(blank=True, related_name='_employee_matched_+', to='users.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, null=True, unique=True)),
                ('type', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='employees', to='users.Skill'),
        ),
    ]
