# Generated by Django 2.1.1 on 2018-10-21 10:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('direct_manager', models.CharField(max_length=30)),
                ('years_of_experience', models.IntegerField()),
                ('years_within_organization', models.IntegerField()),
                ('years_in_role', models.IntegerField()),
                ('study_field', models.CharField(max_length=30)),
                ('is_mentor', models.BooleanField(default=False)),
                ('work_location', models.CharField(max_length=30)),
                ('position', models.CharField(max_length=30)),
                ('departement', models.CharField(max_length=30)),
            ],
        ),
    ]
