# Generated by Django 2.1.1 on 2018-12-12 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='skills',
            field=models.ManyToManyField(blank=True, default=None, related_name='employees', to='users.Skill'),
        ),
    ]
