# Generated by Django 2.1.1 on 2018-12-04 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='matched',
            field=models.ManyToManyField(blank=True, default=None, null=True, related_name='_employee_matched_+', to='users.Employee'),
        ),
    ]
