# Generated by Django 2.1.1 on 2018-12-30 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20181230_1245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='cycles',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='matched',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='skills',
        ),
    ]
