# Generated by Django 2.1.1 on 2018-12-30 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cycles', '0002_cycle_skills'),
        ('users', '0003_auto_20181230_1839'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='cycles',
            field=models.ManyToManyField(blank=True, related_name='employee', to='cycles.Cycle'),
        ),
        migrations.AddField(
            model_name='employee',
            name='matched',
            field=models.ManyToManyField(blank=True, related_name='_employee_matched_+', to='users.Employee'),
        ),
        migrations.AddField(
            model_name='employee',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='employees', to='users.Skill'),
        ),
    ]
