# Generated by Django 2.1.1 on 2018-11-18 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20181024_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='departement',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='direct_manager',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='position',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='study_field',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='work_location',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='years_in_role',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='years_of_experience',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='years_within_organization',
            field=models.IntegerField(null=True),
        ),
    ]