# Generated by Django 2.1.1 on 2018-11-27 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('answers', '0004_auto_20181119_1016'),
        ('users', '0004_auto_20181118_1320'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Employee',
        ),
    ]
