# Generated by Django 2.1.1 on 2019-01-03 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cycles', '0005_cycle_skills'),
        ('users', '0005_auto_20190103_1407'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='employees', to='cycles.Skill'),
        ),
    ]
