# Generated by Django 2.1.1 on 2018-12-04 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20181127_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='matched',
            field=models.ManyToManyField(blank=True, default=None, related_name='_employee_matched_+', to='users.Employee'),
        ),
    ]
