# Generated by Django 2.1.1 on 2018-12-05 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_employee_matched'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, null=True, unique=True)),
                ('type', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='skills',
            field=models.ManyToManyField(related_name='employees', to='users.Skill'),
        ),
    ]
