# Generated by Django 2.1.1 on 2018-10-21 09:42

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('question_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=300)),
                ('is_matching', models.BooleanField(default=False)),
                ('is_mentor', models.BooleanField(default=False)),
                ('type', models.CharField(max_length=300)),
                ('mapped', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='questions.Question')),
            ],
        ),
    ]
