# Generated by Django 2.1.1 on 2018-12-04 11:10

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('question_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question_text', models.CharField(max_length=300)),
                ('is_matching', models.BooleanField(default=False)),
                ('is_mentor', models.BooleanField(default=False)),
                ('user_info', models.CharField(max_length=300)),
                ('question_type', models.CharField(max_length=300)),
                ('mapped', models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='questions.Question')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='question',
            unique_together={('question_text', 'is_mentor')},
        ),
    ]
