# Generated by Django 2.1.1 on 2018-10-31 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_auto_20181030_1342'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='question',
            unique_together={('question_text', 'is_mentor')},
        ),
    ]
