# Generated by Django 2.1.1 on 2018-12-27 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('questions', '0001_initial'),
        ('users', '0001_initial'),
        ('answers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='answer_from_user',
            field=models.ManyToManyField(default=None, related_name='answers_from', to='users.Employee'),
        ),
        migrations.AddField(
            model_name='answer',
            name='answer_to_question',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='questions.Question'),
        ),
    ]
