# Generated by Django 2.1.1 on 2018-12-27 16:02

import django.contrib.postgres.fields.hstore
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('answers', '0002_auto_20181227_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='text',
            field=django.contrib.postgres.fields.hstore.HStoreField(verbose_name=models.CharField(blank=True, max_length=100, null=True)),
        ),
    ]
