# Generated by Django 2.1.1 on 2018-12-04 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('answers', '0002_auto_20181126_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answer_from_user',
            field=models.ManyToManyField(default=None, related_name='answers_from', to='users.Employee'),
        ),
    ]
