# Generated by Django 2.1.1 on 2018-11-14 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20181024_1023'),
        ('answers', '0002_auto_20181112_1430'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='answer_from_user',
        ),
        migrations.AddField(
            model_name='answer',
            name='answer_from_user',
            field=models.ManyToManyField(blank=True, default=None, null=True, to='users.User'),
        ),
    ]
