# Generated by Django 2.1.1 on 2018-12-30 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('answers', '0003_auto_20181227_1802'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='answer_id',
        ),
        migrations.AddField(
            model_name='answer',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
