# Generated by Django 2.1.1 on 2018-11-19 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('answers', '0003_auto_20181114_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answer_from_user',
            field=models.ManyToManyField(blank=True, default=None, null=True, related_name='answers', to='users.User'),
        ),
    ]
