# Generated by Django 2.1.1 on 2018-12-30 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('answers', '0004_auto_20181230_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='original',
            field=models.BooleanField(default=False),
        ),
    ]
