# Generated by Django 2.1.1 on 2018-12-30 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('answers', '0005_answer_original'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='answer_from_user',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='answer_to_question',
        ),
    ]
