# Generated by Django 2.1.1 on 2018-12-30 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20181230_1245'),
        ('answers', '0007_auto_20181230_1303'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='answer_from_user',
        ),
        migrations.AddField(
            model_name='answer',
            name='answer_from_user',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answers_from', to='users.Employee'),
        ),
    ]
