# Generated by Django 2.1.1 on 2018-12-31 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('answers', '0008_auto_20181230_1315'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='text',
        ),
    ]
