# Generated by Django 2.1.1 on 2018-12-31 16:32

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('answers', '0009_remove_answer_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='text',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, size=None),
            preserve_default=False,
        ),
    ]
