# Generated by Django 2.1.1 on 2019-01-01 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('answers', '0010_answer_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answer_from_user',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='users.Employee'),
        ),
    ]
