# Generated by Django 2.1.1 on 2018-12-12 12:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_auto_20181212_1226'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cycle',
            fields=[
                ('cycle_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30, null=True)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('deadline', models.DateTimeField()),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('mentees', models.ManyToManyField(related_name='mentees', to='users.Employee')),
                ('mentors', models.ManyToManyField(related_name='mentors', to='users.Employee')),
                ('skills', models.ManyToManyField(related_name='cycles', to='users.Skill')),
            ],
        ),
    ]
