# Generated by Django 2.1.1 on 2018-12-05 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20181205_1759'),
        ('cycles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cycle',
            name='skills',
            field=models.ManyToManyField(related_name='cycles', to='users.Skill'),
        ),
    ]
