# Generated by Django 2.1.1 on 2018-12-12 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cycles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cycle',
            name='skills',
            field=models.ManyToManyField(blank=True, default=None, related_name='cycles', to='users.Skill'),
        ),
    ]
