# Generated by Django 2.1.1 on 2018-12-26 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cycles', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cycle',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='cycles', to='users.Skill'),
        ),
    ]
