# Generated by Django 2.1.1 on 2018-12-16 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cycles', '0002_cycle_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cycle',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='cycles', to='users.Skill'),
        ),
    ]
