# Generated by Django 2.1.1 on 2019-01-03 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cycles', '0002_cycle_skills'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cycle',
            name='skills',
        ),
    ]
