# Generated by Django 2.1.1 on 2018-12-19 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cycles', '0003_auto_20181216_1839'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deadline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration', models.DateTimeField()),
            ],
        ),
        migrations.RemoveField(
            model_name='cycle',
            name='deadline',
        ),
    ]