# Generated by Django 2.1.1 on 2018-12-23 11:31

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cycles', '0004_auto_20181219_1542'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cycle',
            name='id',
        ),
        migrations.AddField(
            model_name='cycle',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cycle',
            name='cycle_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
