# Generated by Django 2.1.1 on 2019-01-03 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cycles', '0004_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='cycle',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='cycles', to='cycles.Skill'),
        ),
    ]
