# Generated by Django 2.1.1 on 2018-12-23 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cycles', '0005_auto_20181223_1331'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cycle',
            name='cycle_id',
        ),
        migrations.AddField(
            model_name='cycle',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
